### ISSUE TITLE
Very little information about how the number can be used

### ISSUE THREAD

**Issue by ryleu** [pjf/rickastley#15]
I think there should be a file somewhere either in this repo or on the website (or both) that makes it clear how people can use your numbers.

If I set up my own number, can I have it forward calls to your numbers? Is there anything to keep in mind when doing so?

If I’m missing something obvious, then that’s just par for the course, so please let me know.

**Comment by pjf** [comment]
@FourInchKnife : Oh gosh, for the published numbers, I don't think there's any reasonable way I can stop people from using/calling or calling them, so it's really a case of use them as you'd see fit!

Having said that, they do get a *lot* of call volume (500+ calls/day is typical), which means my fun little project now actually costs real money to run, and that means sometimes the service will pause because I've set spending limit triggers. If you're planning to rickroll a *lot* of people, and you *need* to make sure they're never gonna be let down, then provisioning your own number can help you make that guarantee. :)

But if you're forwarding calls to your personal phone to the number, or just rickrolling a few thousand and it's okay if some get dropped, then absolutely go for your life!

~ Paul

**Comment by ryleu** [comment]
Awesome! Good to know. I think I want to forward my calls from scammers to get rickrolled.
