### ISSUE TITLE
Add Swedish number

### ISSUE THREAD

**Issue by secworks** [pjf/rickastley#17]
Aloha!

Here is the number to the Swedish hotline:
+46 766-86-84-36

That service seems to be a clone of this repo at Gitlab:
https://gitlab.com/stemid/rickastley

**Comment by stemid** [comment]
@secworks Thanks for the shout out. That's my repo actually.

It's not really a clone of this repo, because I use a Swedish service called 46elks.se instead of Twilio. Resulting in only 10 lines of Python code for the webhook.

I'd be honored if all numbers were shown in one place. I'm not paying anything for incoming calls to my number.

**Comment by secworks** [comment]
Long time!
I think we can close this one.
